ARRAYS

BASICS

In [98]:
import array as arr

In [99]:
a=arr.array('i',[1,2,3])   #creating an array a
a

array('i', [1, 2, 3])

In [5]:
b=arr.array('i',[1,2,3])  #creating an array b
b

array('i', [1, 2, 3])

SLICING

In [7]:
a[0:]          #slicing

array('i', [1, 2, 3])

In [8]:
a[::1]            #slicing in the forward direction

array('i', [1, 2, 3])

In [9]:
a[::-1]        #slicing in reverse direction

array('i', [3, 2, 1])

In [10]:
a[:0]      #slicing at 0

array('i')

In [11]:
a[:1]      #slicing at 1

array('i', [1])

In [16]:
a.append(4)   #append  of 4 
a

array('i', [1, 2, 3, 6, 6, 4, 4, 4])

In [17]:
b.pop()          #pop operation
b

array('i', [1, 2])

In [18]:
a.pop()         #pop operation
a

array('i', [1, 2, 3, 6, 6, 4, 4])

In [19]:
a

array('i', [1, 2, 3, 6, 6, 4, 4])

In [20]:
a.remove(a[1]) #remove operation
a

array('i', [1, 3, 6, 6, 4, 4])

In [21]:
a

array('i', [1, 3, 6, 6, 4, 4])

In [22]:
a.remove (a[2])   #remove operation
a

array('i', [1, 3, 6, 4, 4])

In [23]:
a.remove (a[3])    #remove operation
a

array('i', [1, 3, 6, 4])

In [24]:
a

array('i', [1, 3, 6, 4])

In [25]:
a.pop()          #pop operation
a

array('i', [1, 3, 6])

In [26]:
a.pop()             #pop opeartion
a

array('i', [1, 3])

In [27]:
b.pop()            #pop opeartion
b

array('i', [1])

In [28]:
b

array('i', [1])

In [29]:
c=arr.array('i',[5,6,9])
c

array('i', [5, 6, 9])

In [30]:
c.pop(1)
c

array('i', [5, 9])

In [31]:
a

array('i', [1, 3])

In [32]:
b

array('i', [1])

In [33]:
b.pop(0)            #pop operation
b

array('i')

In [34]:
for i in c:            #getting all elements
    print(i)

5
9


In [35]:
for i in c:          #getting all elements in c horizantally
    print(i,end=" ")

5 9 

In [37]:
a+b                  #addition operation


array('i', [1, 3])

In [38]:
c+a              #addition opeartion

array('i', [5, 9, 1, 3])

In [39]:
c+b                 #addition opeartion

array('i', [5, 9])

NUMPY

PIP INSTALL NUMPY

In [55]:
import numpy as np           #importing numpy

In [56]:
g=np.array([(4,5,6),(7,8,9)]) #creating a matrix g using numpy
h=np.array([(1,2,3),(3,6,9)]) #creating a matrix h using numpy
g

array([[4, 5, 6],
       [7, 8, 9]])

In [57]:
h

array([[1, 2, 3],
       [3, 6, 9]])

In [58]:
g.ndim      #finding which dimensional matrix is g

2

In [59]:
h.ndim      #finding which dimensional matrix is h

2

In [60]:
g.itemsize  #finding the size of an element of g

4

In [61]:
h.itemsize #finding the size of an element of h

4

In [62]:
h.dtype    #finding data type of h

dtype('int32')

In [63]:
g.size  #finding size of g
g

array([[4, 5, 6],
       [7, 8, 9]])

In [64]:
h.shape     #finding number of rows and coloumnsof h

(2, 3)

In [65]:
h.reshape(3,2)   #changing rows into columns and columns into rows

array([[1, 2],
       [3, 3],
       [6, 9]])

In [66]:
g.min() #finding min value of g

4

In [67]:
g.max() #finding max value of g

9

In [68]:
h.sum()   #finding the sum of h matrix

24

In [70]:
i=np.linspace(2,4,6) #getting 5 values 2 and 4
i

array([2. , 2.4, 2.8, 3.2, 3.6, 4. ])

In [71]:
g.sum(axis=1)   #gettingn sum of elements of rows in g

array([15, 24])

In [72]:
g.sum(axis=0) #getting sum of elements of columns in g

array([11, 13, 15])

In [73]:
np.sqrt(g) #finding square root of all elements in g

array([[2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [74]:
np.std(h) #finding standerd deviation of h

2.70801280154532

In [75]:
np.mean(g) #finding total mean of g

6.5

In [76]:
g

array([[4, 5, 6],
       [7, 8, 9]])

In [77]:
h

array([[1, 2, 3],
       [3, 6, 9]])

In [78]:
g[0,2]  #finding 2nd element of 0th column

6

In [79]:
h[0:2,1]

array([2, 6])

In [80]:
g[1:2,1]

array([8])

In [81]:
g[g>1]    #finding the elements greater than 1

array([4, 5, 6, 7, 8, 9])

In [82]:
h.sort() #finding of elements inascending order
h

array([[1, 2, 3],
       [3, 6, 9]])

In [83]:
h[h<1]  #finding the elements less than 1

array([], dtype=int32)

In [84]:
g+h      #adding of two matrices

array([[ 5,  7,  9],
       [10, 14, 18]])

In [85]:
g*h    #mul of two matrices

array([[ 4, 10, 18],
       [21, 48, 81]])

In [86]:
g.ravel() #getting  of all elements in a same matrix

array([4, 5, 6, 7, 8, 9])

In [87]:
h.ravel() #getting of all elements in a same matrix

array([1, 2, 3, 3, 6, 9])

In [88]:
a.pop() #pop operation
a

array('i', [1])

In [91]:
b

array('i')

In [92]:
c

array('i', [5, 9])

In [93]:
c.pop() #pop operation

9

In [96]:
c

array('i', [5])